# Generated by Django 4.1.7 on 2023-11-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_mymodel_mymodeltranslation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mymodeltranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mymodeltranslation',
            name='master',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ uz',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='MyModelTranslation',
        ),
    ]
