# Generated by Django 4.1.7 on 2023-11-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_mymodeltranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ uz',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
